app:
  url: 'http://roger.swag'
  storage: file
builds:
  concurrent: 5 # max number of builds to run in parallel
  retry-after: 20 # interval, in seconds, for Roger to check whether it can start queued builds
routes:
  config:           '/api/config'
  projects:         '/api/projects'
  build-project:    '/api/build'
  builds:           '/api/builds'
  build:            '/api/builds/:build'
  build-log:        '/api/builds/:build/log'
  build-link:       '/#/projects/:projectName/:build'
  github-hooks:     '/public/api/hooks/github'
paths:
  builds:   '/tmp/roger-builds/'
  sources:  '{{ paths.builds }}/sources'
  tars:     '{{ paths.builds }}/tars'
  logs:     '{{ paths.builds }}/logs'
docker:
  client:
    socketPath: '/tmp/docker.sock'
notifications:
  github:
    global: 'false'
  slack:
    global: 'true'
    channel: '#builds'
    icon_emoji: ':robot_face:'
    username: 'Roger'
